apiVersion: v1
kind: Secret
metadata:
  name: inventorydb-secret
  namespace: storage-system
type: Opaque
stringData:
  inventorydb-root-password: "root-password"
  inventorydb-password: "inventory-password"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventorydb-pvc
  namespace: storage-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventorydb
  namespace: storage-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inventorydb
  template:
    metadata:
      labels:
        app: inventorydb
    spec:
      containers:
        - name: inventorydb
          image: mariadb:10.11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: inventorydb-secret, key: inventorydb-root-password } }
            - name: MARIADB_DATABASE
              value: inventory_db
            - name: MARIADB_USER
              value: inventory_user
            - name: MARIADB_PASSWORD
              valueFrom: { secretKeyRef: { name: inventorydb-secret, key: inventorydb-password } }
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 30
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: inventorydb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: inventorydb
  namespace: storage-system
spec:
  selector:
    app: inventorydb
  ports:
    - port: 3306