apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: root
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            
            - name: config-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
              
            - name: volume-dashboards
              mountPath: /var/lib/grafana/dashboards

            - name: config-alerting
              mountPath: /etc/grafana/provisioning/alerting

      volumes:
        - name: config-datasources
          configMap:
            name: grafana-datasources
            
        - name: config-dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: volume-dashboards
          configMap:
            name: grafana-dashboards

        - name: config-alerting
          configMap:
            name: grafana-alerting

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: storage-system
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300