apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: storage-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      initContainers:
        - name: wait-for-orderdb
          image: busybox:1.36
          command: [ "sh", "-c", "until nc -z orderdb 3306; do echo 'waiting for orderdb...'; sleep 2; done" ]
      containers:
        - name: order-service
          image: ghcr.io/robinb00/order-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: "order_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderdb-secret
                  key: orderdb-password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://orderdb:3306/order_db"
