apiVersion: v1
kind: Secret
metadata:
  name: orderdb-secret
  namespace: storage-system
type: Opaque
stringData:
  orderdb-root-password: "root-password"
  orderdb-password: "order-password"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderdb-pvc
  namespace: storage-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb
  namespace: storage-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb
          image: mariadb:10.11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: orderdb-secret, key: orderdb-root-password } }
            - name: MARIADB_DATABASE
              value: order_db
            - name: MARIADB_USER
              value: order_user
            - name: MARIADB_PASSWORD
              valueFrom: { secretKeyRef: { name: orderdb-secret, key: orderdb-password } }
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 30
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: orderdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orderdb
  namespace: storage-system
spec:
  selector:
    app: orderdb
  ports:
    - port: 3306