server:
  port: 8080
  address: 0.0.0.0

datasource:
  # 'mariadb' matches the Service name defined above
  url: jdbc:mariadb://mariadb:3306/inventory_db
  username: inventory_user
  password: inventory-password
  driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Keeps your table structure
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus