apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-data-service
  namespace: storage-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: master-data-service
  template:
    metadata:
      labels:
        app: master-data-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      initContainers:
        - name: wait-for-masterdb
          image: busybox:1.36
          command: [ "sh", "-c", "until nc -z masterdb 3306; do echo 'waiting for masterdb...'; sleep 2; done" ]
      containers:
        - name: master-data-service
          image: ghcr.io/robinb00/master-data-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: "master_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masterdb-secret
                  key: masterdb-password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://masterdb:3306/master_db"
