apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-data-service
  namespace: storage-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master-data-service
  template:
    metadata:
      labels:
        app: master-data-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: master-data-service
          image: ghcr.io/robinb00/master-data-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: "inventory_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masterdb-secret
                  key: masterdb-password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb:3306/master_db"
