apiVersion: v1
kind: Service
metadata:
  name: master-data-service
  namespace: storage-system
spec:
  type: ClusterIP
  selector:
    app: master-data-service
  ports:
    - port: 8080
      targetPort: 8080
