resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - master-data-service/deployment.yaml
  - master-data-service/service.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
