namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml
- prometheus-grafana/grafana-provisioning.yaml
- prometheus-grafana/grafana-dashboards.yaml
- prometheus-grafana/grafana-dashboard-provider.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: d3a2b915819d5deea87a36c07ba3ee9225896103
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: d3a2b915819d5deea87a36c07ba3ee9225896103
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: d3a2b915819d5deea87a36c07ba3ee9225896103
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: d3a2b915819d5deea87a36c07ba3ee9225896103
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
