namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml
- prometheus-grafana/grafana-provisioning.yaml
- prometheus-grafana/grafana-dashboards.yaml
- prometheus-grafana/grafana-dashboard-provider.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: cde3757544e149078304161a1fc2922a9ced8678
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: cde3757544e149078304161a1fc2922a9ced8678
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: cde3757544e149078304161a1fc2922a9ced8678
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: cde3757544e149078304161a1fc2922a9ced8678
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
