namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: 87cb0707dec3576b0c591169fac7f47b0bca7a4b
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: 87cb0707dec3576b0c591169fac7f47b0bca7a4b
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: 87cb0707dec3576b0c591169fac7f47b0bca7a4b
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: 87cb0707dec3576b0c591169fac7f47b0bca7a4b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
