namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: 3b5e63e9044ce951b2560c57c197adc7d03a6160
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: 3b5e63e9044ce951b2560c57c197adc7d03a6160
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: 3b5e63e9044ce951b2560c57c197adc7d03a6160
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: 3b5e63e9044ce951b2560c57c197adc7d03a6160
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
