namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: 76e0380cec0300748f6e205c58fc9c3ea6d0c78c
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: 76e0380cec0300748f6e205c58fc9c3ea6d0c78c
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: 76e0380cec0300748f6e205c58fc9c3ea6d0c78c
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: 76e0380cec0300748f6e205c58fc9c3ea6d0c78c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
