namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml
- prometheus-grafana/grafana-provisioning.yaml
- prometheus-grafana/grafana-dashboards.yaml
- prometheus-grafana/grafana-dashboard-provider.yaml
- prometheus-grafana/grafana-alerting.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: 44b7b810f8977fc37f8518562f7864b52f5d86ab
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: 44b7b810f8977fc37f8518562f7864b52f5d86ab
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: 44b7b810f8977fc37f8518562f7864b52f5d86ab
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: 44b7b810f8977fc37f8518562f7864b52f5d86ab
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
