namespace: storage-system

resources:
- ../../base
- prometheus-grafana/prometheus-deployment.yaml
- prometheus-grafana/grafana-deployment.yaml
- prometheus-grafana/prometheus-configmap.yaml
- prometheus-grafana/prometheus-rbac.yaml
- prometheus-grafana/grafana-provisioning.yaml

images:
- name: ghcr.io/robinb00/api-gateway
  newName: ghcr.io/robinb00/api-gateway
  newTag: b767719107938ccefeffface94ed1ac15b0e8370
- name: ghcr.io/robinb00/inventory-service
  newName: ghcr.io/robinb00/inventory-service
  newTag: b767719107938ccefeffface94ed1ac15b0e8370
- name: ghcr.io/robinb00/master-data-service
  newName: ghcr.io/robinb00/master-data-service
  newTag: b767719107938ccefeffface94ed1ac15b0e8370
- name: ghcr.io/robinb00/order-service
  newName: ghcr.io/robinb00/order-service
  newTag: b767719107938ccefeffface94ed1ac15b0e8370
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
