name: Build and Deploy (GitOps)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build services (Maven)
        run: mvn -B clean package -DskipTests

      - name: Build & push Docker images
        run: |
          for service in api-gateway master-data-service order-service inventory-service; do
            docker build \
              -t $IMAGE_PREFIX/$service:${{ github.sha }} \
              -f $service/Dockerfile \
              .
            docker push $IMAGE_PREFIX/$service:${{ github.sha }}
          done

      - name: Update Kustomize image tags
        run: |
          cd k8s/overlays/dev

          kustomize edit set image \
            $IMAGE_PREFIX/api-gateway=${IMAGE_PREFIX}/api-gateway:${{ github.sha }}

          kustomize edit set image \
            $IMAGE_PREFIX/master-data-service=${IMAGE_PREFIX}/master-data-service:${{ github.sha }}

          kustomize edit set image \
            $IMAGE_PREFIX/order-service=${IMAGE_PREFIX}/order-service:${{ github.sha }}

          kustomize edit set image \
            $IMAGE_PREFIX/inventory-service=${IMAGE_PREFIX}/inventory-service:${{ github.sha }}

      - name: Commit updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s/overlays/dev/kustomization.yaml
          git commit -m "Update images to ${{ github.sha }}"
          git push
